apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
    name: gitops-cluster-test
    namespace: test
spec:
    argoServer:
        cluster: local-cluster
        argoNamespace: argocd
    placementRef:
        kind: Placement
        apiVersion: cluster.open-cluster-management.io/v1alpha1
        name: all-openshift-clusters
