name: Cypress
on:
    pull_request:
        branches: main
jobs:
    cypress:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
            - run: npm ci
            - run: cd testing && npm ci
            - run: cd testing && npm run e2e
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: testing/cypress/screenshots
