name: Pull Request
on:
    pull_request:
        branches: main
jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install CLI tools from OpenShift Mirror
              uses: redhat-actions/openshift-tools-installer@v1
              with:
                  source: 'mirror'
                  oc: '4'
            - run: oc login --token ${{ secrets.TOKEN }} ${{ secrets.APISERVER }} --insecure-skip-tls-verify=true
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
            - run: npm ci
            - run: npm run setup
            - run: npm run cypress:ci
            - name: 'Upload Artifact'
                uses: actions/upload-artifact@v3
                with:
                    path: cypress/screenshots
                    retention-days: 1    
